apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- prometheus-config.yaml
- prometheus-deployment.yaml
- prometheus-rbac.yaml
- llm-observability-servicemonitor.yaml
- kuadrant-servicemonitors.yaml

labels:
- pairs:
    environment: base
    project: llm-observability
