apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: llm-observability-self
  labels:
    app: llm-observability
spec:
  endpoints:
  - interval: 30s
    port: web
  selector:
    matchLabels:
      app: llm-observability
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm-simulator-monitor
  labels:
    app: vllm-simulator
spec:
  endpoints:
  - interval: 30s
    port: http
    path: /metrics
  selector:
    matchLabels:
      app: vllm-simulator
  namespaceSelector:
    matchNames:
    - llm
