apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llm-observability

resources:
- ../../prometheus
- namespace.yaml

configurations:
  - kustomizeconfig.yaml

labels:
- pairs:
    environment: default
    project: llm-observability
